<?php

namespace Acme\TabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RSSCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RSSCacheRepository extends EntityRepository
{
}
